### ISSUE TITLE
Choosing Quick Menu > Restart causes hard crash of RetroArch 

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/FreeIntv#20]
1. Load _freeintv_ core
2. Load _content_
3. Choose _Run_
4. Open RetroArch _Quick Menu_
5. Choose _Restart_

**Expected**
Should soft reset core and reload content.

**Actual**
Hard Crash. 

**Versions**
RA 1.7.1
FreeIntv 1.0

**Comment by recompileorg** [comment]
All better

**Comment by Keltron3030** [comment]
Just wanted to point out that this issue is back.  Maybe the original fix was reverted at some point?

Using Retroarch 1.9.0 nightly FreeIntv 1.1

**Comment by recompileorg** [comment]
> 
> 
> Just wanted to point out that this issue is back. Maybe the original fix was reverted at some point?
> 
> Using Retroarch 1.9.0 nightly FreeIntv 1.1

The change wasn't reverted, though I really wish I had explained why that seemingly pointless change fixed this before.

**Comment by gingerbeardman** [comment]
For yourself or for others? 😅

**Comment by recompileorg** [comment]
For me, of course.  It would sure make fixing this a second time easier!

**Comment by Keltron3030** [comment]
Fixed with #66 and should be closed.

**Comment by recompileorg** [comment]
Why can't I close issues?

**Comment by gingerbeardman** [comment]
Until then I'll close this issue (cos it's mine)
