### ISSUE TITLE
Crashes loading "MTE201 Intellivision Test Cartridge"

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/FreeIntv#21]
[MTE201 Intellivision Test Cartridge.int.zip](https://github.com/libretro/FreeIntv/files/1951113/MTE201.Intellivision.Test.Cartridge.int.zip)

**Testing**
ROM loads as Baseball(!) in _jzIntv_.
ROM runs fine in _OpenEmu/Bliss_, see below:

![mte201 intellivision test cartridge 2018-04-26 13 29 31](https://user-images.githubusercontent.com/49612/39305734-fde6b398-4955-11e8-9124-c75e7a7c5f96.png)

**Comment by recompileorg** [comment]
The range for one of the loading methods was wrong.  I think this is the only cart that uses load method 8 though.  

Things would be so much easier if everyone just used intellicart formatted roms :)
