### ISSUE TITLE
load3() and load9() seem to be identical?

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/FreeIntv#23]
Not sure if they should be different or if it is duplication that can be removed.

```c
void load3()
{
	loadRange(0x5000, 0x6FFF);
	loadRange(0x9000, 0xAFFF);
	loadRange(0xD000, 0xDFFF);
	loadRange(0xF000, 0xFFFF);
}
```
used by fingerprints:
- Tower of Doom (1986) (Matel)

```c
void load9()
{
	loadRange(0x5000, 0x6FFF);
	loadRange(0x9000, 0xAFFF);
	loadRange(0xD000, 0xDFFF);
	loadRange(0xF000, 0xFFFF);
} 
```
used by fingerprints:
- Game Factory (Prototype) (1983) (Mattel)
- Triple Challenge (1986) (Intv Corp)

**Comment by gingerbeardman** [comment]
Ah, memory map information here (and downloads):
https://retropie.org.uk/docs/Intellivision/

shows that load9() needs

```
[memattr]
$8800 - $8FFF = RAM 8
```

**Comment by recompileorg** [comment]
That marks the range 8800 - 8FFF in the first case and D000 - D3FF in the second as 8-bit wide memory.  This emulator enforces very few rules with regard to RAM, ROM, and memory width, so if a game expects a certain range to be RAM that would normally be ROM, for example, it'll work just fine.  

As a consequence of that apathy, load4 and load9 end up being the same.
