### ISSUE TITLE
Button priority issue (Astrosmash)

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/FreeIntv#27]
I'm not familiar with this game so apologies if it's meant to be like this. 

One press of the fire button shoots one missile. 
Left and right move the ship. 

But if you hold down the action button, each press of left or right emits a missile on button down _and_ button up!

Video: http://www.youtube.com/watch?v=KGSuhuAcjog

This feels like an emulation issue to me, but I could be wrong! 

I've looked at videos of the game on YouTube and cannot spot this odd behaviour.

**Comment by recompileorg** [comment]
This is, apparently, the correct behavior.   I dug in to the controls for a while, then checked it in other emulators.  Both Bliss and jsIntv do the same thing.

**Comment by gingerbeardman** [comment]
Apologies, I really should have tested this one with Bliss and OpenEmu like I did with the other issues.

**Comment by recompileorg** [comment]
No worries.  It's better to err on the safe side rather than risk ignoring a bug.
