### ISSUE TITLE
[ERROR] [FREEINTV] HALT! at 6385

### ISSUE THREAD

**Issue by telanus** [libretro/FreeIntv#29]
- Which version of RetroArch are you using?
Version: 1.7.5 Git: 62eb782

- What system hardware are you using?

```
System:    Kernel: 4.15.0-38-generic x86_64 bits: 64 Desktop: KDE Plasma 5.12.7
           Distro: Ubuntu 18.04.1 LTS
Graphics:  Card: NVIDIA GT215 [GeForce GT 240]
           Display Server: x11 (X.Org 1.19.6 ) drivers: nvidia (unloaded: modesetting,fbdev,vesa,nouveau)
           Resolution: 1360x768@60.02hz
           OpenGL: renderer: GeForce GT 240/PCIe/SSE2 version: 3.3.0 NVIDIA 340.107
```

- What did you do?
Try to load a rom via retroarch

- What did you expect to happen?
That it run

- What happened instead?
It crashed

Log 1: https://pastebin.com/59WhfncN  < loading a rom from goodintv
Log 2: https://pastebin.com/dakYAMUp < loading from tosec
Log 3: https://pastebin.com/jyDPV2J0    < loading from nostalgia

**Comment by recompileorg** [comment]
I tried ABPA Backgammon in Windows 10 and Retropie 4.4 on a RaspberryPi 3 B and it's working correctly.

Try updating to the latest version, if you haven't already.  

Can anyone try this on Ubuntu 18.04 ?
