### ISSUE TITLE
Move to /libretro org?

### ISSUE THREAD

**Issue by RobLoach** [libretro/FreeIntv#4]
This is awesome! Nicely done. Tested it out with Burger Time, and it worked well.

Couple questions...

- Did we add a .info file to libretro-super?
- Is there any plan to move it to the /libretro org?
- Had made a mirror of it over at https://github.com/libretro-mirrors/freeintv ... Want me to delete it?
- What ports have you gotten working? 
- Want some help adding the libretro-super recipes?

**Comment by markwkidd** [comment]
@RobLoach great to see you here!

1. Yes we did. That is to say you created one, and I tweaked the supported extensions :) https://github.com/libretro/libretro-super/blob/master/dist/info/freeintv_libretro.info
2. That would be great. It's been in my repository here while the essentials were setup in terms of Makefile/buildbot and documentation but I would not prefer to have long-term responsibility for the repo. What's the next step to move it to the libretro organization?
3. Mirror: This repo has a commit history going all the way back to those versions of the source files, so I don't see a specific need for that mirror unless it's useful for archival/reference purposes
4. Platforms: I think it's working well in Windows 7+ x64, Linux x64, rpi, and NES classic and SNES classic. Others are unknown at this point.
5. Recipe help: yes please! I don't know any more than what we have now in terms of recipes, and I suspect that not all recipes are working even as they are.

**Comment by markwkidd** [comment]
The latest news is that this repo is now located in the libretro github organization.

I think that puts the focus on the build recipes and cross-platform troubleshooting. We've gotten it building for many platforms and there is pretty comprehensive integration with the buildbot. There are lots of systems where we have no feedback yet on whether the builds are functional.

* Android: Building, but neither of the two Android users who posted could load content
* OS X: Building, not tested
* iOS: Building, not tested
* Emscripten: Building but I can't get any emulator to work in Emscripten locally so I can't test
* PlayStation 2: Building for each of the PS2 variants, not tested
* PS Vita: Building, not tested
* Nintendo consoles: I can't tell if it's building for these

**Comment by markwkidd** [comment]
FreeIntv not building for Linux x86_32: https://github.com/libretro/FreeIntv/issues/11

**Comment by markwkidd** [comment]
* Twinaphex contributed build fixes for PS Vita and Emscripten: https://github.com/libretro/FreeIntv/commit/1c4959359573619c65d789a89ecd3b5f05d30ca2
* I discovered how to that the libretro buildbot logs are accessible via the libretro discord server! whoa!
* FreeIntv is definitely building for Nintendo 3DS, Gamecube, Wii, and WiiU
* FreeIntv is not building for the PSP as well as older Windows and xbox MSVC compilers, which I suspected but now that I have logs I can attempt to figure out the secrets of MSVC makefiles. 

If anyone else wants to take a look at the failing PSP build, here is the link:

`<retrobot> freeintv: [status: fail] [recipes/playstation/psp] LOG: http://p.0bl.net/158438`

Here are links the MSVC build logs:

    <retrobot> freeintv: [status: fail] [recipes/windows/cores-windows-msvc2010-x64_seh-generic] LOG: http://p.0bl.net/158457
    <retrobot> freeintv: [status: fail] [recipes/windows/cores-windows-msvc2010-x86_dw2-generic] LOG: http://p.0bl.net/158459
    <retrobot> freeintv: [status: fail] [recipes/windows/cores-windows-msvc2017-desktop-x64_seh-generic] LOG: http://p.0bl.net/158461
    <retrobot> freeintv: [status: fail] [recipes/windows/cores-windows-msvc2017-desktop-x86_dw2-generic] LOG: http://p.0bl.net/158462
    <retrobot> freeintv: [status: fail] [recipes/windows/cores-windows-msvc2017-uwp-x64_seh-generic] LOG: http://p.0bl.net/158464
    <retrobot> freeintv: [status: fail] [recipes/windows/cores-windows-msvc2017-uwp-x86_dw2-generic] LOG: http://p.0bl.net/158465
    <retrobot> freeintv: [status: fail] [recipes/windows/cores-windows-msvc2017-uwp-arm-generic] LOG: http://p.0bl.net/158466
    <retrobot> freeintv: [status: fail] [recipes/windows/cores-windows-msvc2003-x86_dw2-generic] LOG: http://p.0bl.net/158468
    <retrobot> freeintv: [status: fail] [recipes/windows/cores-windows-msvc2005-x86_dw2-generic] LOG: http://p.0bl.net/158469

**Comment by markwkidd** [comment]
Seems like we made it to libretro! :)

**Comment by RobLoach** [comment]
Woooooo!

**Comment by gingerbeardman** [comment]
I'm using this on N3DS and I just wanted to say great work!
