### ISSUE TITLE
Intellivania not working on emulator

### ISSUE THREAD

**Issue by Darknior** [libretro/FreeIntv#40]
Hi
So bad but with last Libretro Engine and last FreeIntv Core this demo not working and crashing the emulator. When i load the rom on Windows it close Libretro !

https://www.youtube.com/watch?v=VQMd06fWkHI

Wish some one update this core to fix all these problems i can read here...
Thanks

**Comment by Darknior** [comment]
Hi :) 
No news about this problem ?
The autor also working on a Prince of Persia and Megaman for Intellivision ... so impressive work !!!
It can be cool if some one can try to understand why this game is not loading fine on emulator and working fine on real hardware ?
Thanks

**Comment by recompileorg** [comment]
I somehow missed this issue.  I guess that's what happens when there aren't many contributors and our time is, unfortunately, very limited.   

Anyhow, I'm now aware of the issue.   I'll try to get to it.

**Comment by Darknior** [comment]
@recompileorg thanks a lot, i wish you will found a solution :)

**Comment by recompileorg** [comment]
I was able to fix the loading issue, but there are other problems with the demo, some minor graphics issues, for example.   

Do you happen to know if this game uses bank switching?  That's not currently supported, but only because I didn't have a game to test it.

**Comment by Darknior** [comment]
There is no full version release for now ... only a demo :(
But many games like this one are coming, all the news games dev in IntelliBasic i think.
Intellivania, the future Intelli Prince of Persia, Intelli Megaman, the old Stonix, the recent Defender of the Crown ... and the future Papi Commando :)

The only rom for the moment you can found to try is Stonix, and it include a MAPPING file ...
http://knox.ac.free.fr/index.php/inty/roms?title=stonix
I can't make it working too on lr-FreeIntv ... i don't understand.

**Comment by recompileorg** [comment]
Stonix seems to work fine.   I'll try to update the release on SourceForge today, if you don't want to wait for the buildbot.

**Comment by Darknior** [comment]
Thanks a lot really :)
Many gamers will now can try this incredible DEMO :)
I will stand the buildbot, because i use Batocera and we will update this core when it will be possible :)
