### ISSUE TITLE
Permission sought from recompileorg - Permission to add FreeIntv to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [libretro/FreeIntv#43]
Hi there @recompileorg,

we would like to seek your permission to include FreeIntv as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by recompileorg** [comment]
I don't see anything wrong with it off-hand.  As long as the user knows where to get the source and license, it should be in compliance with the GPLv3.
