### ISSUE TITLE
Expose RAM for Retroachievement creation

### ISSUE THREAD

**Issue by Keltron3030** [libretro/FreeIntv#44]
Hello,

At [Retroachievements](http://www.retroachievements.org) we are always looking to support more emulators for achievement creation.  If one of the freeintv developers here could allow the RAM to be exposed we can then use our tools to develop achievements for this great system.

**Comment by recompileorg** [comment]
I don't mind, but I have no idea what it means to "allow the RAM to be exposed".   If you can point me to the relevant documentation, I'll be happy to make the change.

**Comment by Jamiras** [comment]
RetroArch and RALibRetro use the `retro_get_memory_data` and `retro_get_memory_size` methods exposed via the libretro interface to access the `RETRO_MEMORY_SYSTEM_RAM` and `RETRO_MEMORY_SAVE_RAM`.

We also support the `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` callback, but that's typically only needed for more complex systems.

**Comment by recompileorg** [comment]
That was easier than expected.  Let me know if this needs anything else.

**Comment by Jamiras** [comment]
I suspect that you're going to want to put an `if (id == RETRO_MEMORY_SYSTEM_RAM)` in front of those, or it'll also return the system memory for SRAM and/or VRAM. If a system doesn't have dedicated SRAM or VRAM, it should just return NULL/0 when queried.

**Comment by recompileorg** [comment]
Good to know.  Where is this documented, or are we supposed to divine this from libretro.h?

**Comment by Jamiras** [comment]
I don't know if the docs actually go into any more detail, or if there's anywhere else where you should look. Most of the achievements implementation was already present when I became involved. I did find this in libretro.h near the constants: https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h#L287-L309
but nothing near the function prototypes.

**Comment by recompileorg** [comment]
Thanks.  I'm going to also add this to FreeChaF.  It also has video ram, and should make for an easy-to-understand example.
