### ISSUE TITLE
Intermittent failure to load cart

### ISSUE THREAD

**Issue by Sanaki** [libretro/FreeIntv#47]
More often than not (about 9/10 loads), loading Astrosmash (and presumably other games) results in a screen showing a failure to load cart, followed by a grid of characters and a core halt (killing retroarch with it). Other than the following lines, nothing else abnormal appears in terminal output. The opcode and halt point shown are consistent.
```
[ERROR][FREEINT] Bad opcode: 8240


[ERROR] [FREEINTV] HALT! at 10604
```
![LOAD CART FAIL](https://user-images.githubusercontent.com/1374333/79527179-75caf700-8056-11ea-9fbf-6ef43a2ace61.png)
![Character Grid](https://user-images.githubusercontent.com/1374333/79527198-7cf20500-8056-11ea-8652-8153965173fe.png)

* FreeIntV 1.1 self-compiled (510749917761416b2ed6319d7bbcb7501e7860a0)
* Retroarch 1.8.5 self-compiled (https://github.com/libretro/RetroArch/commit/018a0baed64d921e800dc94dc9ebf2ed19537a10)
* GCC 9.2.1 64-bit
* Linux Mint 64-bit (kernel 5.3.0-46)

Games are no-intro verified in int format, problem arises both inside a 7z archive and extracted.

**Comment by recompileorg** [comment]
Make sure you have read permissions for the rom that you're trying to load.

**Comment by Sanaki** [comment]
I do. That it succeeds around 10% of the time is proof of that.

**Comment by recompileorg** [comment]
Not really.  My guess is that you're sometimes running as root and sometimes as a differently privileged user.

**Comment by Sanaki** [comment]
No, I'm loading under the exact same conditions always. I literally hit close content and reopen the game without closing out retroarch. I also would never allow something like retroarch elevated permissions. All directories it uses, without exception, are owned by me with read access present.

**Comment by recompileorg** [comment]
What is being reported in the output?

**Comment by Sanaki** [comment]
Pretty much the same thing, other than the lines from above. I restarted retroarch until success this time, just to get a clean log.

[Load Fail log](https://github.com/libretro/FreeIntv/files/4497709/freeintvfail.txt)
[Load Success log](https://github.com/libretro/FreeIntv/files/4497710/freeintvsuccess.txt)

**Comment by recompileorg** [comment]
Try making that error non-fatal.  Why both feof and ferror are set is a mystery.

Comment out line 69 in `cart.c`:
````
 if (ferror(fp))
{
		printf("[ERROR] [FREEINTV] Cartridge load error indicator set\n");
		//return 0;
}
````

**Comment by Sanaki** [comment]
Yeah, that allows it to load reliably. If you need me to test anything else, let me know.
