### ISSUE TITLE
[Feature Request] Add Intellivoice Support

### ISSUE THREAD

**Issue by Keltron3030** [libretro/FreeIntv#52]
A request to add support for the intellivoice module to this core.  

https://en.m.wikipedia.org/wiki/Intellivoice

Intellivoice supported games:
- Space Spartans
- Bomb Squad
- B-17 Bomber
- Tron: Solar Sailer
- Intellivision World Series Baseball

Some technical info that might be useful from jzintv:
http://spatula-city.org/~im14u2c/intv/tech/ivoice.html

I've started a bounty to which I hope other enthusiasts might contribute in order to help make this a reality.

https://www.bountysource.com/issues/96185381-feature-request-add-intellivoice-support

**Comment by Keltron3030** [comment]
This has been added by @nanochess with #67.  Thank you for this.  I tested with B-17 Bomber and Bomb Squad and it works great.

I hope you'll claim the $25 bounty as a small token of my appreciation.  😊

**Comment by Eusino** [comment]
Thanks for intellivoice support! 😃
Thanks !
But is Intellivision World Series Baseball working?
Because I'm testing it and I only get the green screen "INTELLIVISION HALTED"

**Comment by nanochess** [comment]
> Thanks for intellivoice support! 😃 Thanks ! But is Intellivision World Series Baseball working? Because I'm testing it and I only get the green screen "INTELLIVISION HALTED"

It requires ECS. Not yet supported.
