### ISSUE TITLE
Please add to iOS nightlies (iOS-arm64)

### ISSUE THREAD

**Issue by trotsky40** [libretro/FreeIntv#55]
This core was present in the last stable (1.90). Please add to the most recent iOS nightlies (iOS-arm64). Thank you.

**Comment by twinaphex** [comment]
OK, added them.

**Comment by trotsky40** [comment]
Thank you. That was my last existing playlist from 1.90 that didn’t have a core. Now onto the wishlist (dosbox- pure, I am looking at you) 😊
