### ISSUE TITLE
Audio crackling on some games with FreeIntv

### ISSUE THREAD

**Issue by quicksilver7837** [libretro/FreeIntv#7]
I noticed that when running some games using FreeIntv, there is a crackling noise coming through my speakers. It isnt present for all games and it seems mainly to happen on Mattel games (triple action, astrosmash), though I have heard it on others as well. The crackling noise goes away when the game is paused. I tested these same games using jzintv and there is no audio issues when using that emulator.

**Comment by recompileorg** [comment]
This fixed the crackling on my windows 10 computer and rpi3.
